%% this is where I will build my final analysis for the project

% Using a 902 cortical ROI x 35 ROI cerebellum file generated by conn_full_rois.
%
% Below are the settings I used:
% civet_format = 1;
% tr_s = 0.7;
% tr_n = 1200;
% filt_lo_hz = 0.009;
% filt_hi_hz = 0.08;
% filt_order = 100;
% tested_runs = [1, 2, 3, 4];
% update_func = 1;
% update_volu = 1;
% update_grey = 1;
% use_ctx_mask = 1;
% use_filter = 1;

addpath(genpath('/home/jdv/code/cerebellum'))
%inname = 'compcor-1000-dil_nopass_func-volu-grey_vertex_CV_proc.mat';
load('curr-ana-final-1000_2018.mat');
%outname = 'curr-ana-final-1000_2018.mat';
parpool

g_volu_ctx = corr(ctx_volu);
g_volu_sub = corr(sub_volu);
g_thck_ctx = corr(ctx_thck);
g_thck_sub = corr(sub_thck);
g_grey_ctx = corr(ctx_grey);
g_grey_sub = corr(sub_grey);
g_func_ctx = calc_g_func(ctx_func, nsub*nrun);
g_func_sub = calc_g_func(sub_func, nsub*nrun);
g_func_sub_2ndord = corr(r_func');
g_volu_sub_2ndord = corr(g_volu');
g_thck_sub_2ndord = corr(g_thck');

% Q1 -- overview of data
figure; % data-overview.fig
subplot(2,3,1); [H, T, perm] = dendrogram_plot(g_func_ctx, [], [], 1, 1);
subplot(2,3,2); dendrogram_plot(g_volu_ctx, [], perm, 1, 1);
subplot(2,3,3); dendrogram_plot(g_thck_ctx, [], perm, 1, 1);
subplot(2,3,4); [H, T, perm] = dendrogram_plot(r_func, labels, [], 0.5, 0);
subplot(2,3,5); dendrogram_plot(g_volu, labels, perm, 0.5, 0);
subplot(2,3,6); dendrogram_plot(g_thck, labels, perm, 0.5, 0);

% Q2 Structrure function at ROI level
n_iter = 10000;
[func_volu_rs, func_volu_ps, func_volu_sig] = permutation_test(g_func, g_volu, n_iter, 97.5);
[func_thck_rs, func_thck_ps, func_thck_sig] = permutation_test(g_func, g_thck, n_iter, 97.5);
[volu_thck_rs, volu_thck_ps, volu_thck_sig] = permutation_test(g_volu, g_thck, n_iter, 97.5);

figure; % func-struct-roi.fig
subplot(3,1,1)
plot_labels = star_labels(labels, func_volu_sig');
bar(func_volu_rs, 'FaceColor', [0 0 0], 'EdgeColor', [0 0 0]);
set(gca, 'xtick', [1:35]);
set(gca, 'xticklabel', plot_labels);
xlim([0.5 35.5])
ylim([-0.4 0.4])

subplot(3,1,2)
plot_labels = star_labels(labels, func_thck_sig');
bar(func_thck_rs, 'FaceColor', [0 0 0], 'EdgeColor', [0 0 0]);
set(gca, 'xtick', [1:35]);
set(gca, 'xticklabel', plot_labels);
xlim([0.5 35.5])
ylim([-0.4 0.4])

subplot(3,1,3)
plot_labels = star_labels(labels, volu_thck_sig');
bar(volu_thck_rs, 'FaceColor', [0 0 0], 'EdgeColor', [0 0 0]);
set(gca, 'xtick', [1:35]);
set(gca, 'xticklabel', plot_labels);
xlim([0.5 35.5])
ylim([0 0.5])

% cortical atlas -- for mappings
fname = fopen(['ctx_roi_civ.L.1D'], 'rt');
fdata = textscan(fname, '%f%f%f%f%f%f%f', 'Whitespace', ' ', 'MultipleDelimsAsOne', 1, 'HeaderLines', 5);
ctx_tmp_maskL = fdata{7};
fclose(fname);
fname = fopen(['ctx_roi_civ.R.1D'], 'rt');
fdata = textscan(fname, '%f%f%f%f%f%f%f', 'Whitespace', ' ', 'MultipleDelimsAsOne', 1, 'HeaderLines', 5);
ctx_tmp_maskR = fdata{7};
fclose(fname);

ctx_mask = [ctx_tmp_maskL; ctx_tmp_maskR];
ctx_rois = unique(ctx_mask(ctx_mask > 0));

% export
%idx_to_nifti('100307/T1w/parcellation_1000-dil.nii.gz', func_volu_ctx_rs, ctx_rois, 'ctx-func-volu.nii.gz');
%idx_to_nifti('100307/T1w/parcellation_1000-dil.nii.gz', func_thck_ctx_rs, ctx_rois, 'ctx-func-thck.nii.gz');
idx_to_nifti('100307/proc/smoothmask.01.nii.gz', func_volu_rs, [], 'cere-func-volu.nii.gz');
idx_to_nifti('100307/proc/smoothmask.01.nii.gz', func_thck_rs, [], 'cere-func-thck.nii.gz');
idx_to_nifti('100307/proc/smoothmask.01.nii.gz', volu_thck_rs, [], 'cere-volu-thck.nii.gz');

% Q3: cross-modal similarity of clustering
clst_sub = [2:1:10];

inst_func = clusterestimate(g_func, clst_sub, n_iter);
inst_thck = clusterestimate(g_thck, clst_sub, n_iter);
inst_volu = clusterestimate(g_volu, clst_sub, n_iter);

figure;
errorbar(inst_func.mean, inst_func.sd, 'linewidth', 2, 'color', 'black');
hold on;
errorbar(inst_thck.mean, inst_thck.sd, 'linewidth', 2, 'color', 'red');
errorbar(inst_volu.mean, inst_volu.sd, 'linewidth', 2, 'color', 'blue');
set(gca, 'xtick', [1:length(clst_sub)]);
set(gca, 'xticklabel', clst_sub);
ylim([0 1])
legend('BOLD', 'volume-thickness', 'volume-volume')
xlabel('instability')
ylabel('number of clusters')

% Q4: determine how similar clustering of the cerebellum is across the 3 methods
% obvious best number of clusters is 2
dist_fxn = 'euclidean';
link_fxn = 'ward';
n = 2;

func_Y = pdist(g_func, dist_fxn);
func_Z = linkage(func_Y, link_fxn);
func_C = cluster(func_Z,'maxclust', n);

thck_Y = pdist(g_thck, dist_fxn);
thck_Z = linkage(thck_Y, link_fxn);
thck_C = cluster(thck_Z,'maxclust', n);

volu_Y = pdist(g_volu, dist_fxn);
volu_Z = linkage(volu_Y, link_fxn);
volu_C = cluster(volu_Z,'maxclust', n);

mappings = match_labels(thck_C, func_C);
thck_C_out = zeros(length(thck_C), 1);
for x = 1:n;
    idx = find(thck_C == x);
    thck_C_out(idx) = mappings(x);
end
thck_C = thck_C_out;

mappings = match_labels(volu_C, func_C);
volu_C_out = zeros(length(volu_C), 1);
for x = 1:n;
    idx = find(volu_C == x);
    volu_C_out(idx) = mappings(x);
end
volu_C = volu_C_out;

all_C = [func_C, thck_C, volu_C];

sparseness = 0.1;


ctx_merged_func = merge_by_cluster(g_func, func_C');
ctx_merged_thck = merge_by_cluster(g_thck, thck_C');
ctx_merged_volu = merge_by_cluster(g_volu, volu_C');

ctx_merged_func_sparse = make_sparse(ctx_merged_func, sparseness);
ctx_merged_thck_sparse = make_sparse(ctx_merged_thck, sparseness);
ctx_merged_volu_sparse = make_sparse(ctx_merged_volu, sparseness);

print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_func, ctx_rois, 'ctx-mean-corrs-func-');
print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_thck, ctx_rois, 'ctx-mean-corrs-thck-');
print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_volu, ctx_rois, 'ctx-mean-corrs-volu-');

print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_func_sparse, ctx_rois, 'ctx-mean-corrs-func-sparse-');
print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_thck_sparse, ctx_rois, 'ctx-mean-corrs-thck-sparse-');
print_out_data('100307/T1w/parcellation_1000-dil.nii.gz', ctx_merged_volu_sparse, ctx_rois, 'ctx-mean-corrs-volu-sparse-');


%save(outname, '-v7.3')
% eva marder -- carb connectivity
% marcus richel
